/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DOtherSideJNI */

#ifndef _Included_DOtherSideJNI
#define _Included_DOtherSideJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DOtherSideJNI
 * Method:    qapplication_create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DOtherSideJNI_qapplication_1create
  (JNIEnv *, jclass);

/*
 * Class:     DOtherSideJNI
 * Method:    qapplication_exec
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DOtherSideJNI_qapplication_1exec
  (JNIEnv *, jclass);

/*
 * Class:     DOtherSideJNI
 * Method:    qapplication_quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DOtherSideJNI_qapplication_1quit
  (JNIEnv *, jclass);

/*
 * Class:     DOtherSideJNI
 * Method:    qapplication_delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_DOtherSideJNI_qapplication_1delete
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
